export enum PagesEnum {
  login = 'login',
  signup = 'signup',
  profileDetails = 'profileDetails',
  profileDetailsEdit = 'profileDetailsEdit',
  profilePasswordEdit = 'profilePasswordEdit',
  profileAvatarEdit = 'profileAvatarEdit',
  error5xx = 'error5xx',
  error4xx = 'error4xx',
  chatboard = 'chatboard',
  modalAddChat = 'modalAddChat',
  modalAddUser = 'modalAddUser',
  modalDeleteUser = 'modalDeleteUser',
  chatMessage = 'chatMessage',
}
